database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: mysecretpassword
  database: microservice_menu

server:
  http:
    host: "0.0.0.0"
    port: 8080
  grcp:
    port: 50051